### ISSUE TITLE
Detect MP4

### ISSUE THREAD

**Issue by odan** [selective-php/video-type#1]

**Comment by peter279k** [comment]
According to `MPEG-4` [video detection approach](https://github.com/h2non/filetype.py/blob/master/filetype/types/video.py#L9), the `MPEG-4` will have the following bytes in the first 12 bytes.
```ftypmp42```

The `ftyp` bytes should have in `MPEG-4` video file.

The next `4` bytes are about the `MPEG-4` file type brands and it will be the `mp42` or `mp41`.

They also should have these brand versions.
