### ISSUE TITLE
Detect MPEG-1 Part 2

### ISSUE THREAD

**Issue by odan** [selective-php/video-type#19]
MPEG-1 Part 2 (Video-CD)

* https://en.wikipedia.org/wiki/MPEG-1
* http://hubblesource.stsci.edu/sources/video/clips/
* https://en.wikipedia.org/wiki/List_of_file_signatures

Magic bytes:

```
00 00 01 B3
```

**Comment by qligier** [comment]
MPEG-1 is already detected by the [MpegDetector](https://github.com/selective-php/video-type/blob/master/src/Detector/MpegDetector.php#L28), the README could be updated to reflect that?

**Comment by odan** [comment]
That's correct. Could you please create a PR to update the README?
