### ISSUE TITLE
Detect WEBM video format

### ISSUE THREAD

**Issue by peter279k** [selective-php/video-type#6]
As title, and useful reference is available [here](http://fileformats.archiveteam.org/wiki/Webm).

**Comment by peter279k** [comment]
Just notice that the `WebM` has the same identification situation as `OGG`.

It has the same identification approach for `video/webm` and `audio/webm` MIME types.

**Comment by odan** [comment]
## Specification

* https://www.webmproject.org/docs/container/
* https://www.w3.org/2013/12/byte-stream-format-registry/webm-byte-stream-format.html
* http://fileformats.archiveteam.org/wiki/Webm

## Identification

* A WebM file begins with `0x1a 0x45 0xdf 0xa3`, as do all EBML files.

* It contains an EMBL "DocType" element whose value is the string "webm". This means that the byte sequence 0x42 0x82 0x84 'w' 'e' 'b' 'm' will appear in the file, normally near the beginning.
