### ISSUE TITLE
Detect OGG format

### ISSUE THREAD

**Issue by peter279k** [selective-php/video-type#7]
As title, and the reference is available [here](http://fileformats.archiveteam.org/wiki/Ogg).

According to this reference, this format has the possible situations.

The one is about `audio/ogg` and another one `video/ogg`, but the MIME type is `application/ogg`.

I think it's fine to do this format detection and return the `application/ogg` MIME type.

**Comment by peter279k** [comment]
BTW, I just provide the [link ](http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5)about sample video files.

It includes the `WEBM`, `OGG`, `3GP` and `MPEG-4` sample video files.

**Comment by odan** [comment]
BTW: We should add all OGG related discussions here (for later documentation).

**Comment by odan** [comment]
## Specification

* https://tools.ietf.org/html/rfc5334#section-10.2

## Identification

The first four bytes, 0x4f 0x67 0x67 0x53, correspond to the string "OggS".

This applies for video/ogg and audio/ogg.

A substring like `video/theora` could be an additional indicator for `video/ogg`.

**Comment by peter279k** [comment]
Ok. I see that. It looks different on the last byte. One is `s` and another one is `S`.

**Comment by peter279k** [comment]
Here are the `OGG` audio and video files.

- [OGG video](http://techslides.com/demos/sample-videos/small.ogv)
- [OGG audio](https://file-examples.com/index.php/sample-audio-files/sample-ogg-download/)

**Comment by odan** [comment]
Sorry, It's always "OggS" and not "Oggs". I just updated the identification section.

**Comment by peter279k** [comment]
It looks same detection approach after reading the `OGG` RFC specification.
